version: "3.8"
services:
  frontend:
    container_name: next_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    # volumes:
    #   - ./frontend:/var/www/html/frontend
    networks:
      - app
  nginx:
    container_name: nginx
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    # volumes:
    #   - ./frontend:/var/www/html/frontend
    #   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - app
networks:
  app:
    driver: bridge
volumes:
  enlive-vendor:




