version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/sites-available/default.conf
    depends_on:
      - client
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    # ports:
    #   - "7777:7777"
    volumes:
      - /app/node_modules # node_modules won't override
      - ./client:/app # everything inside would share with App folder
    # environment:
    #   - REDIS_HOST=redis   # furture reference for setting env vars

